image: gradle:6.5.0-jdk14

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/caches

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  DOCKER_DRIVER: overlay2

stages:
  - test

test-common:
  script:
    - gradle clean :common:test --info

test-sqlparser:
  script:
    - gradle clean :sqlparser:test --info

test-stmt:
  script:
    - gradle clean :sqlparser:stmt --info

